### ISSUE TITLE
Error with translate plugin

### ISSUE THREAD

**Issue by evwerkz** [mplodowski/dynamicpdf-plugin#101]
https://github.com/mplodowski/dynamicpdf-plugin/blob/84e0d6b5ed1957dceb30cdee881891d190176301/classes/PDFWrapper.php#L86

I have some errors by make a pdf. 
**Error: Access to undeclared static property RainLab\Translate\Models\Message::$locale**

October V3.1
Translate Ver.2

And new function to become a local is App::getLocale();

If I delete this line, it works fine. But I don't know in general what this line is needed for.

**Comment by evwerkz** [comment]
![image](https://user-images.githubusercontent.com/49227960/195342654-8020d6be-0abd-45d7-8676-73bc1aca72d5.png)

**Comment by mplodowski** [comment]
Should be fixed in version 7.0
