### ISSUE TITLE
Permissions denied

### ISSUE THREAD

**Issue by kristianstroka** [mplodowski/dynamicpdf-plugin#102]
I have clean installation of octobercms running locally in MAMP pro (mac m1). I have problem with library, since in every path (css or fonts, or images) I got this error (when warning messages are on)

Error loading /Users/asdf/Documents/projekty/project1/storage/app/uploads/public/634/419/96d/63441996db6a4004839876.png: Permission denied. The file could not be found under the paths specified by Options::chroot. /Users/asdf/Documents/projekty/project1/storage/app/uploads/public/634/419/96d/63441996db6a4004839876.png Error loading /Users/asdf/Documents/projekty/project1/storage/app/uploads/public/5fa/c0e/aa1/5fac0eaa13bc3962668422.jpg: Permission denied. The file could not be found under the paths specified by Options::chroot. /Users/asdf/Documents/projekty/project1/storage/app/uploads/public/5fa/c0e/aa1/5fac0eaa13bc3962668422.jpg Unable to parse image URL themes/lidl/assets/img/png/cas.png. themes/lidl/assets/img/png/cas.png Unable to parse image URL themes/lidl/assets/img/png/porcie.png. themes/lidl/assets/img/png/porcie.png Unable to parse image URL themes/lidl/assets/img/png/narocnost.png. themes/lidl/assets/img/png/narocnost.png Error loading /Users/asdf/Documents/projekty/project1//storage/app/uploads/public/5fa/c0e/aa1/5fac0eaa1678a136063018.jpg: Permission denied. The file could not be found under the paths specified by Options::chroot. /Users/asdf/Documents/projekty/project1//storage/app/uploads/public/5fa/c0e/aa1/5fac0eaa1678a136063018.jpg

I tried to set 777 chmod for storage folder (just for testing) but same results. Template is loaded only from admin, also cant load template from specific plugin (path is correct, since in previous version of plugin (5.x and october 1) it works correctly, and as I can see therre is no changes on that... Can you help me, or at least how to find out which permissions or where Iˇm missing? Thanks

**Comment by mplodowski** [comment]
It seems like chroot issue for dompdf configuration.

You can publish config:

`php artisan vendor:publish --provider="Barryvdh\DomPDF\ServiceProvider"`

Then go to `/config/dompdf.php` and check `chroot` option. You can try to set it to `/` for testing purpose.

**Comment by kristianstroka** [comment]
If I change chroot to "/" behaviour doesnt change ... still same error response

**Comment by mplodowski** [comment]
Are demo templates works fine?

https://github.com/mplodowski/dynamicpdf-plugin#demo-examples
