### ISSUE TITLE
Plugin is creating a 'public' folder

### ISSUE THREAD

**Issue by abrenoch** [mplodowski/dynamicpdf-plugin#105]
**Describe the bug**
The plugin is creating a `public` folder in the root of the project folder when using `artisan serve` (and other commands)

**To Reproduce**
1. Install latest version of plugin
2. Run `php artisan serve`
3. A `public` folder is created in the project root

**Expected behavior**
No folder is created

**October version**
3.3

**Plugin version**
7.0.1

Looking at what's actually happening here, `SyncTemplates->handle` is being called on the plugin boot. Inside that function is a `$this->checkPublicDir()` call that creates the public folder if it does not exist. 

This folder does not seem to be referenced any where else in the plugin, nor does it *seem* to be required the plugin to work... Wondering why it is there?

With the current behavior not only does it create the `public` folder when one isn't needed, but if a public folder does exist already ***it will create another one within*** upon using `artisan serve`

https://github.com/mplodowski/dynamicpdf-plugin/blob/ea50b54a9dc9da8146df177a381078a5b32f88ea/classes/SyncTemplates.php#L19

https://github.com/mplodowski/dynamicpdf-plugin/blob/ea50b54a9dc9da8146df177a381078a5b32f88ea/classes/SyncTemplates.php#L95-L100

**Comment by mplodowski** [comment]
Hi,

yes this was added before the fix was available for laravel dompdf package - https://github.com/barryvdh/laravel-dompdf/pull/890

I removed this code in plugin version 7.1.0 as it is no longer required.

Thank you for this report.
