### ISSUE TITLE
Cannot resolve public path

### ISSUE THREAD

**Issue by Majstrova** [mplodowski/dynamicpdf-plugin#108]
**Describe the bug**
Preview return error "Cannot resolve public path".

**Screenshots**
![image](https://github.com/mplodowski/dynamicpdf-plugin/assets/31473264/b4293956-a7ac-4c66-8a10-f06c36385bc6)

**October version**
3.4.10

**Plugin version**
7.1.0

**Comment by AllARTSoftworks** [comment]
@Majstrova you need to publish the config this way:

`php artisan vendor:publish --provider="Barryvdh\DomPDF\ServiceProvider" `

then open config/dompdf.php and change this line:

`'public_path' => null`

into this

`'public_path' => public_path()`
