### ISSUE TITLE
Imag Path on Server (question)

### ISSUE THREAD

**Issue by alexax73** [mplodowski/dynamicpdf-plugin#33]
# I having trouble getting an Image working on my server. 
The direct path generated with the {{ url }} / to my image is working fine.
but i does not showig up. i get "Image not found or type unknown" and a outlined box.

local enviromet works fine.

app/config.php has the correct server name too.

any help would be appreciated

**Comment by TimFoerster** [comment]
I replace all relative links with the absolute on.
Works fine for me for generating pdf's with inline images with HTML editor

```php 
// HTML
$htmlContent = ... 

// Get domain
// => http://example.com
$url = url('/');

// Replace all src with url+src
$replacedContent = preg_replace( '/src="\/([^"]*)"/i', 'src="'.$url.'/$1"', $htmlContent);

$data = ['title' => $title, 'content' => $replacedContent]; 

return PDF::loadTemplate($templateCode, $data)->stream();
```

give it a try.

**Comment by mplodowski** [comment]
Check that `allow_url_fopen` is set to true and that the GD extension is enabled in your PHP configuration.

**Comment by alexax73** [comment]
So i checked in my Plesk Backend, allow_url_fopen is true
the option ->setOptions([
        'isRemoteEnabled' => true,
    ]) is now set,
the path is hardcoded (not the twig one)
and still not working

i assume that GD is enabled, thumbnail creation is working.

// the server is currently protected by .htaccess login during development that should be not a problem ?

**Comment by mplodowski** [comment]
I don't know the reason why this is not working for you.

You will have to debug this on your own. Output the path to the image file in your PDF and try different approaches with relative/absolute paths and make sure that the image file is located there.

**Comment by alexaxhauck** [comment]
checked one hour with the hosting agency on that issue, compared local and online Environment. double checkt nearly evertything. the plugin won't create images in the pdf! any idea ?

**Comment by alexaxhauck** [comment]
if i put the filename in like this `
/var/www/vhosts/myiste.de/www1.mydomain.de/storage/app/media/_mediathumbs/highres_no-logo-01-4711.p02.MyImage-Charcoal-c456b41e73b2518273eeb6c1cd97ff1f.jpg
`
i see a image in the pdf. (online)

further i noticed that the retuned value from $_SERVER['DOCUMENT_ROOT'] differs
on local maschine i have  a ending slash - online not

if i use the `{{ product_image.image_filename |mediathumb_resize('width', 600, 96) }}`

i get  `storage/app/media/_mediathumbs/highres_no-logo-01-4711.p02.MyImage-Charcoal-c456b41e73b2518273eeb6c1cd97ff1f.jpg` which is ok. but it wont render in the PDF 

so my hardcoded logo with the complet epath on the maschine works fine.

there is an issuse somewhere - any idea ?

**Comment by mplodowski** [comment]
Probably `allow_url_fopen` is disabled on your hosting and this not allows to render image with `http://`.

Everything depends on your host configuration, there is no issue with PDF library here. There are functions like `base_path()` that will render full path on your server.

**Comment by mplodowski** [comment]
Reference: https://github.com/mplodowski/dynamicpdf-plugin/issues/42
