### ISSUE TITLE
This plugin does not translate strings

### ISSUE THREAD

**Issue by xseguib** [mplodowski/dynamicpdf-plugin#38]
I'm rendering PDF's with this plugin but I noticed that for example {{ 'Price'|_ }} is not working.

Any plans to make this working with rainlab.translate plugin?

Cheers

**Comment by mplodowski** [comment]
I wrote response for your review. Please check it out.

As for the new feature I think it is a good idea and will make it work on my free time.

You're welcome to send PR.

**Comment by mplodowski** [comment]
Added in version 3.0.1.
