### ISSUE TITLE
PHP 7.1 error in php-svg-lib

### ISSUE THREAD

**Issue by Verbat** [mplodowski/dynamicpdf-plugin#44]
I got an "A non-numeric value encountered" error which is already described and should be fixed at the   php-svg-lib where the error occurs? Can you updated your pluing so it include the latest changes.

https://github.com/PhenX/php-svg-lib/commit/0a9869529a2a5f0bee31ba905bdc39962eba1025

Thanks

**Comment by mplodowski** [comment]
This is an issue with dompdf library, not the plugin.

https://github.com/dompdf/dompdf/pull/1476

We will have to wait for this to be fixed there.
