### ISSUE TITLE
No block-level parent found. Not good.

### ISSUE THREAD

**Issue by JortJacobs** [mplodowski/dynamicpdf-plugin#47]
![screen shot 2017-11-07 at 12 04 10](https://user-images.githubusercontent.com/33451643/32490741-8e8d607c-c3b4-11e7-95cf-42bd1f9d01c6.png)

**Comment by JortJacobs** [comment]
Fix: https://github.com/dompdf/dompdf/commit/ad41b6dd17ba774b017407ffba09c14a66665723

**Comment by mplodowski** [comment]
As you said it is related to vendor dependencies.

In my plugin I am using https://github.com/barryvdh/laravel-dompdf

This issue is mentioned here: https://github.com/barryvdh/laravel-dompdf/issues/399

It should be fixed in dompdf 0.8.1 version.

Try to update composer dependencies. This issue is not connected to plugin source files.

**Comment by JortJacobs** [comment]
Even after composer update, it does not work.

**Comment by mplodowski** [comment]
Sorry, this should be fixed in version 0.8.2.

https://github.com/dompdf/dompdf/releases/tag/0.8.2

Please update composer dependencies again and let me know.

**Comment by JortJacobs** [comment]
If I run composer update it does not show the dompdf package is updated?

**Comment by mplodowski** [comment]
In both of my projects it downloads version 0.8.2 after composer update.

Run `composer update`in October project root.

The check version of dompdf: `composer show dompdf/dompdf`

**Comment by JortJacobs** [comment]
Yes it is fixed now, your plugin was installed via OctoberCMS plugins attached to the project. That is why composer update had no effect I think. I reinstalled it from command line with composer and now it is working fine.

**Comment by mplodowski** [comment]
Ok, great. I rebuilt source files for October gateway, so it should be fine there as well.
