### ISSUE TITLE
Default size for layout

### ISSUE THREAD

**Issue by Samuell1** [mplodowski/dynamicpdf-plugin#48]
Hey, its a way to set default paper size in layout?

**Comment by mplodowski** [comment]
Please write with details what you are trying to do.

**Comment by Samuell1** [comment]
Like selecting default paper size in administration for layout

**Comment by mplodowski** [comment]
As you can see this is not possible at the moment.

In documentation there is an example how to do this programatically.

I will consider to add this option in the future in the backend.

**Comment by Samuell1** [comment]
Hey, i see you implemented this in latest version. Thanks a lot! @mplodowski
