### ISSUE TITLE
Use the HTML for emails 

### ISSUE THREAD

**Issue by mbloska** [mplodowski/dynamicpdf-plugin#52]
Can I pull the html for the PDF and use it for emails as well? 

```
if(!empty($pdf)){
          return PDF::loadTemplate('my-farewell-wishes', $data)->download('myfarewellwishes.pdf'); 
        }

        if(!empty($sendEmial)){

          $message = '
          <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
          <html xmlns="http://www.w3.org/1999/xhtml">
          <head>``
         . return PDF::loadTemplate('my-farewell-wishes', $data);  //add the html here <----

```

**Comment by mplodowski** [comment]
Mail Templates are for emails. So just copy HTML to mail template and use them instead.

Most likely email HTML and pdf HTML will not be compatible.

I don't see any reason to use pdf HTML for emails.

Please write what is your goal here.

**Comment by mbloska** [comment]
Thanks for the reply.

To have one themplate to edit in the CMS. To make it easier to up keep. So a user feels out a form and has the option of email or download.

Hope that gives a clearer understanding of what I'm trying to achieve.

**Comment by mplodowski** [comment]
Ok I understand the whole idea, but I don't recommend you this approach.

There will be many different issues with HTML for email and PDF. Those should be kept seperated. Email templates are rendered differently wilth different email clients. They should be code with only tables and there are many restrictions to code them. PDF HTML is not so strict, but it depends on library you use to generate it. In my plugin I use dompdf library, so you must prepare HTML to follow this library guildlines and HTML tags support.

**Comment by mbloska** [comment]
Cool will keep them separate. Thanks for the info.
