### ISSUE TITLE
How to read the page number

### ISSUE THREAD

**Issue by azaharizaman** [mplodowski/dynamicpdf-plugin#54]
Hi there, how do we read the page number generated and display it in the PDF?

Thanks

**Comment by mplodowski** [comment]
This works for me:

```
$pdf = PDF::loadTemplate('renatio::invoice');

$dom_pdf = $pdf->getDomPDF();
$dom_pdf->render();

$canvas = $dom_pdf->get_canvas();
$canvas->page_text(0, 0, "Page {PAGE_NUM} of {PAGE_COUNT}", null, 12);

return $dom_pdf->stream('document.pdf', ['Attachment' => false]);
```

**Comment by SaifurRahmanMohsin** [comment]
How do I add this to the page directly? Is there no markdown way like say adding it in a footer using {{page}} like I can do with {{content_html}} for page content?
