### ISSUE TITLE
How to use partials in DynamicPDF

### ISSUE THREAD

**Issue by HugoWijdeveld** [mplodowski/dynamicpdf-plugin#56]
Hi Renatio,

When I try to use {% partial 'partialname' %} in a template, I get an error report saying

    Unknown "partial" tag in "__string_template__4ebf2d420e6d5528cee7cb511aa2ca8a26fa9f5e2dacf238bf2e9a3cc805edbb" at line 19.
    *path*\vendor\twig\twig\lib\Twig\Parser.php line 158

Is there any way or workaround so I can use partials in DynamicPDF?? I'm on build 434 by the way.

**Comment by StrangerPings** [comment]
@HugoWijdeveld I am also getting the same error, did you manage to find a solution?

**Comment by qroft** [comment]
What is the status of this issue currently? Do i have touse the workaround or am i missing something?
I can pass a variable like this:
`{% partial "mypartial" count=10%}`

I can show said variable, count, on my PDF through {{count}}.
But as soon as i want to use that variable in the PHP code part through **$count= $this->count;** i get the "unknown partial tag" error shown up.

**Comment by AllARTSoftworks** [comment]
@HugoWijdeveld your post was really inspiring. 

I changed it a bit, tested and working on WinterCMS.

In Plugin.php:

```

use \Winter\Storm\Support\Facades\Twig;
use \Illuminate\Support\Facades\File;

public function registerMarkupTags()
    {
        return [
            'functions' => [
                'partial' => function ($args = []) {
                    foreach ($args as $key => $arg) {
                        $vars[$key] = $arg;
                    }
                    $file = $vars['file'];
                    $partial = File::get(plugins_path() . '/me/myplugin/views/pdf/partials/' . $file . '.htm');
                    return Twig::parse($partial, $vars); // using Winter
                },
            ]
        ];
    }```


then in my view, as per your reply:
```
    {{ partial({
        file: 'my_partial_filename',
        title: 'My Title',
    }) }}
```
and in my partial, in /me/myplugin/views/pdf/partials/my_partial_filename.htm:

```
<table class="my-class">
    <tr>
        <td>
            {{ title }}
        </td>
    </tr>
</table>
```
Hope it helps.
