### ISSUE TITLE
Undefined index: DOMPDF_FONT_CACHE

### ISSUE THREAD

**Issue by MajorasJack** [mplodowski/dynamicpdf-plugin#60]
Getting the below error message randomly when attempting to run any basic laravel commands:

`[2018-05-10 12:43:58] dev.ERROR: ErrorException: Undefined index: DOMPDF_FONT_CACHE in /Users/jack/Work/sites/psg/plugins/renatio/dynamicpdf/classes/ServiceProvider.php:33`

Tried looking around and found issue #1260  but none of the resolutions/fixes mentioned there seem to fix the issue that I'm having.

Already tried:
Deleting vendor folder & running `composer update`
Deleting /storage/fonts directory content
`composer dump-autoload`
`composer dump-autoload -o`

Changed all references of DOMPDF_FONT_CACHE to font_cache which appears to have fixed the issue, but don't think it's ideal.

**Comment by mplodowski** [comment]
This should be already fixed: https://github.com/mplodowski/dynamicpdf-plugin/commit/764bb7f11a7768941f1c4ee155a96d782c7e15a2

Try to run `composer update` inside plugin folder and after that inside project folder.

**Comment by MajorasJack** [comment]
I've tried to run `composer update` inside the plugin folder and I'm just getting this:
`Composer could not find a composer.json file in plugins/renatio/dynamicpdf`
Making the change manually to the relevant file in #764bb7f still doesn't appear to fix the issue either.

**Comment by mplodowski** [comment]
It looks like you have old version of dompdf library.

Check your version with: `composer show dompdf/dompdf`

October removes composer.json file from plugin, when it is installed using October gateway. You can  always grab and copy composer.json file from this repository.
