### ISSUE TITLE
Queued PDF job doesn't add CSS styles

### ISSUE THREAD

**Issue by alvaro-canepa** [mplodowski/dynamicpdf-plugin#61]
When I use `save` method, CSS content is not added to PDF like using `stream` method.

## Using `save` method
```php
$view = View::make(
    'planetadeleste.payslip::pdf.invoice_report_header',
    [
        'business' => $business,
        'process'  => ['name' => $this->trans('Reporte MTSS')]
    ]
);
PDF::loadLayout('report', ['content_html' => $view])->save($pdfCoverPath);
```
### Pdf Render
![image](https://user-images.githubusercontent.com/5142298/42573839-9001064c-84f3-11e8-8edf-a045599c0c5c.png)

## Using `stream` method
```php
$view = View::make(
    'planetadeleste.payslip::pdf.invoice_report_header',
    [
        'business' => $business,
        'process'  => ['name' => 'Reporte MTSS']
    ]
);
return PDF::loadLayout('report', ['content_html' => $view])->stream($pdfCoverFilename);
```
### Pdf Render
![image](https://user-images.githubusercontent.com/5142298/42573918-c2115fce-84f3-11e8-85bb-500d2765e724.png)

**Comment by alvaro-canepa** [comment]
I think the problem is when the PDF is saved using Queue jobs, if is saved throw browser, using `save()->stream()` works fine.

**Comment by mplodowski** [comment]
I think that your application URL (/config/app.php) is not set correctly. This value is used for queued jobs. The default is `http://localhost`. Change it and restart queue.

**Comment by alvaro-canepa** [comment]
The application URL is right, this is not the problem.

**Comment by alvaro-canepa** [comment]
I found a problem. Using `@import url('/themes/payslip/assets/css/pdf.css');` doesn't work for queued PDF.
I use the .css content without `@import` and show css styles. But with broken images and doesn't work the position fixed for header and footer elements.

See the result, without images, background image and positioning elements.
![image](https://user-images.githubusercontent.com/5142298/42622525-f6762ecc-8596-11e8-89cb-f7106cae0eb9.png)

**Comment by alvaro-canepa** [comment]
Ok, I found the problem. `@import` must need the full URL, the same for images. 
Thanks for your help!!!

**Comment by mplodowski** [comment]
No problem! 👍
