### ISSUE TITLE
Save()->stream() chaining make parts of lines in generated PDF disappear

### ISSUE THREAD

**Issue by anastasiauz** [mplodowski/dynamicpdf-plugin#62]
Hi! Strange bug in Chrome: if I chain PDF::loadTemplate(...)->save()->stream() - the file looks corrupted, always different lines but always corrupted. Here is the code, what am I doing wrong? My PDF is in Cyrillic, Dejavu Sans, I don't know if it can make any difference. I tried other fonts - same result. Without save() in chain - everything ok.
```
$user = Auth::getUser();
$offer = $user->kp;
    if ($offer) {
        $orientation = $offer->orientation;
        $filename = Str::slug($user->company . '_' . $offer->client_name) . '.pdf';
        return PDF::loadTemplate('offer::classic', compact('user','offer'))
                    ->setPaper('a4', $orientation)       
                    ->setOptions([
                        'logOutputFile' => storage_path('temp/log.htm'),
                        'isRemoteEnabled' => true,                      
                    ])             
                    ->save($filename)
                    ->stream();
     }
```
While the saved file looks totally ok, the streemed version on frontend is not: here is printscreen http://joxi.ru/a2XzoZXc1MDWBr and here is the file 
[smartpx-p-ooo-vilki-i-lozhkip.pdf](https://github.com/mplodowski/dynamicpdf-plugin/files/2296817/smartpx-p-ooo-vilki-i-lozhkip.pdf)

It's not a big problem - I can save the file and then redirect to it but I wonder why? It's in documentation: 
`You can chain the methods:
return PDF::loadTemplate('renatio::invoice')
    ->save('/path-to/my_stored_file.pdf')
    ->stream();
`

**Comment by mplodowski** [comment]
Yeah, I replicated this issue. I think this is more an external library issue, than a plugin itself.

For workaround you can extract this code:

```
protected function makePDF($data, $orientation)
{
    return PDF::loadTemplate('offer::classic', $data)
        ->setPaper('a4', $orientation)
        ->setOptions([
            'logOutputFile' => storage_path('temp/log.htm'),
            'isRemoteEnabled' => true,
        ]);
}
```

and call it double times:

```
$this->makePDF(compact('user', 'offer'), $orientation)->save($filename);
        
return $this->makePDF(compact('user', 'offer'), $orientation)->stream();
```

It is not ideal, but it works.

Or just save PDF and redirect to the file, as you mentioned.

**Comment by anastasiauz** [comment]
Thank you! Saving and redirecting is ok for me. Great plugin, very helpful!
