### ISSUE TITLE
Full page background image

### ISSUE THREAD

**Issue by snipiba** [mplodowski/dynamicpdf-plugin#63]
Background image with proper params (96DPI, approx 794x 1123px) and PDF result was deformed, with scaled image, not to full page but with margin on right side, and image was not at full page, but it overflows at bottom of page. some help or info?

**Comment by mplodowski** [comment]
Hi,

sorry for late response. Please upgrade to the newest version and read again docs about background image.

Try to reset default styles: https://gist.github.com/DavidWells/18e73022e723037a50d6

If you need more help, than I would need coding samples.
