### ISSUE TITLE
Header on every page and long content splitted over pages

### ISSUE THREAD

**Issue by NayaStudio** [mplodowski/dynamicpdf-plugin#64]
I want to create PDF with header contain some address text and information on pages of pages in PDF (like 1/10 pages), and below that i want to put some long content generated from data by twig for ... 

and have issue that after auto content page brake, on next page content is placed over the header at top of page :/
and second thing... page numbers - how to get them ?

**Comment by mplodowski** [comment]
Hi, 

sorry for late response. Please update to latest version of the plugin.

As for Header please read docs about Header and Footer and there is an example code.

As for page numbers it cannot be done without embedding PHP:

https://github.com/dompdf/dompdf/wiki/Usage#embedded-php-support

I will try to simplify using page numbers in the future.
