### ISSUE TITLE
Image in template return error 503

### ISSUE THREAD

**Issue by Ladylain** [mplodowski/dynamicpdf-plugin#72]
Hi 

i'm using DynamicPDF since a lot of time, and it's the first time i have this problem. 

When i try to generate my pdf, if this one has an image into it, the generation is very slow and most of the time ends with an error 503. 

All was working in local, and when i have upload my october environnement into my FTP, this thing came up. 

UPDATE: sometimes i get this error 
>
>file_get_contents(http://dev.mvtransport.fr/storage/app/media/logo_mvtransport_w250.png): failed to open stream: Connection timed out Image not found http://dev.mvtransport.fr/storage/app/media/logo_mvtransport_w250.png
/var/www/clients/client1/web23/web/plugins/renatio/dynamicpdf/vendor/barryvdh/laravel-dompdf/src/PDF.php line 211

UPDATE 2 : I have just tried to put an image link to google logo, (so on another server) and all seems to work perfectly. 
i think there is an issue with my server

does someone have an idea how to fix this please ? 

Best, 

L.

**Comment by mplodowski** [comment]
Hi,

sorry for late response. Please upgrade plugin to newest version.

I just used your example image with <img> tag and it works fine.
