### ISSUE TITLE
Update to version 3.0.4 on marketplace

### ISSUE THREAD

**Issue by Flynsarmy** [mplodowski/dynamicpdf-plugin#73]
Version 3.0.3 currently the latest on the October CMS marketplace is breaking composer installations due to incompatible versions of illuminate packages specified in your composer.json. This has since been fixed in version 3.0.4's composer.json in this git repo. Could you please do a pull of the latest version onto the marketplace?

**Comment by mplodowski** [comment]
Hi,

sorry for late response.

Done.
