### ISSUE TITLE
How to append additional (premade) PDF files?

### ISSUE THREAD

**Issue by lanrosta** [mplodowski/dynamicpdf-plugin#75]
I have a pre-made instruction sheet PDF file that I would like to append to the end of my DynamicPDF file. How can I achieve this with the DynamicPDF plug-in? I don't ant to have to 'recreate' the existing PDF file inside the Template. I'd simply like to append an existing PDF file to the one that gets generated via DynamicPDF.

**Comment by az-vm** [comment]
Hello,

I need this to! any one can help us?

Regard´s
Vitor

**Comment by mplodowski** [comment]
Hi,

sorry for late response.

It is not possible with dompdf library.

Please read this: https://stackoverflow.com/questions/14701776/how-to-merge-pdf-using-dompdf/14701818
