### ISSUE TITLE
Displaying images in tempate

### ISSUE THREAD

**Issue by Corymillz** [mplodowski/dynamicpdf-plugin#76]
In my code i have this
````
 $icon = ['file' => $file];
 PDF::loadTemplate($templateCode, $data, $icon)->setOptions(['isRemoteEnabled' => true])->stream('download.pdf');
````
when i ````dd( $icon = ['file' => $file]);```` i get the image in array pulled from ````$file = Auth::getUser()->avatar; ````

but in the template when i do 
````
    <img scr="{{ file.getThumb(40, 40) }}" />
````
 nothing shows up. Am i missing something?

**Comment by mplodowski** [comment]
Hi,

sorry for late response.

The `$data` variable is array that you need to pass.

You should write this like so:

```
 $data = ['file' => $file];
 PDF::loadTemplate($templateCode, $data)->setOptions(['isRemoteEnabled' => true])->stream('download.pdf');
```
