### ISSUE TITLE
Example on how to call DB templates and layouts?

### ISSUE THREAD

**Issue by qroft** [mplodowski/dynamicpdf-plugin#83]
Though i have not tried it out, i understand the solution on how to use this plugin through the plugin/-->views/pdf etc. folder just like it is mentioned on the OctoberCMS market and also here on the Github documentation.

I think i understood everything in theory, but i am absolutely unable to render my template created within the OctoberCMS backend. Does there exist an example for this way?

What i have done so far:
1. Installed the plugin
2. Created a layout called "default" and a template called "invoice"

**Comment by mplodowski** [comment]
There is Preview button in backend for layouts and templates.

In documentation first example is how to stream pdf to browser. Just place this code inside your controller or component.

**Comment by qroft** [comment]
My misunderstanding was this:
On the plugin documentation the "how to use it as a plugin" is absolutly fantastic described.
But i wanted to use the option calling the tempalte not from as a plugin, but from the DB.

So if anyone comes across this and ahs the same misunderstanding:
There are 2 ways on how to call a template.

Way one: as a plugin using **author.plugin::pdf.layouts.default** (but with your autor and layout/template)

Way two: use the octobercms-backend --> settings --> PDF templates
Here create your layout and template and then call it simply like in this example:
`
    $storagePath =  storage_path('app/uploads/invoices/');
    $pdf_file_name =  "testinvoice.pdf" ;
    $pdf_file_name_directory =  $storagePath . $pdf_file_name;

        $templateCode = 'my-own-invoice'; // unique code of the template set up in the OctoberCMS backend.
        PDF::loadTemplate($templateCode)
            ->setPaper('a4', 'portrait')
            ->save($pdf_file_name_directory);
`
