### ISSUE TITLE
Custom template error

### ISSUE THREAD

**Issue by mkinternet** [mplodowski/dynamicpdf-plugin#85]
When i create and register template i got error "No query results for model [Renatio\DynamicPDF\Models\Template]". I have to run dynamicpdf plugin settigns page then template is "seen" by plugin.

Steps to produce error.

Create template in /plugins/myorg/myplugin/views/pdf/mytemplate.htm
Register plugin in /plugins/myorg/myplugin/Plugin.php using:

	public function registerPDFTemplates()
	{
		return [
			'myorg.myplugin::pdf.mytemplate',
		];
	}	

Run template in a plugin 
return \Renatio\DynamicPDF\Classes\PDF::loadTemplate('myorg.myplugin::pdf.mytemplate', $data)->stream();

**Comment by AllARTSoftworks** [comment]
Same here. Identical issue.

**Comment by oscartorrescarrion** [comment]
hello, did you manage to solve the problem?

**Comment by mkinternet** [comment]
No i didn't i workaround it by running dynamicpdf  plugin.

**Comment by chocolata** [comment]
I found out that if you create a custom layout, you can copy over the code that is being shown in the DynamicPDF settings: 
![image](https://user-images.githubusercontent.com/3584586/229505998-ac8d9971-d4dc-434c-afe2-997dfed218bf.png)

That seems to work.
