### ISSUE TITLE
custom font not working anymore

### ISSUE THREAD

**Issue by johnnywo** [mplodowski/dynamicpdf-plugin#88]
After updating to latest version of plugin I realized that **my custom font was replaced with standard helvetica**.
This is what I have in my template layout in css section:

    @font-face {
    font-family: 'Montserrat';
    src: url('storage/fonts/Montserrat-Regular.ttf');
    }

    @font-face {
    font-family: 'Montserrat';
    font-weight: bold;
    src: url('storage/fonts/Montserrat-Bold.ttf');
    }

```
body {
font-size: 36px;
font-family: 'Montserrat', sans-serif;
margin: 0px;
padding: 150px 250px 10px 250px;
background-repeat: no-repeat;
background-position: 0 0;
}
```
any idea what was causing this?   
Thank you!

**Comment by mplodowski** [comment]
Maybe something has change in dompdf library that handles the CSS url, but in my opinion you should always use absolute path. So you should change your code to this:

```
@font-face {
font-family: 'Montserrat';
src: url('/storage/fonts/Montserrat-Regular.ttf');
}

@font-face {
font-family: 'Montserrat';
font-weight: bold;
src: url('/storage/fonts/Montserrat-Bold.ttf');
}
```

Now you should just ensure the font is inside the directory: `/storage/fonts/`.

**Comment by johnnywo** [comment]
thanks for your answer! Just tried that but unfortunately it does not solve the problem. Fonts are located in the bespoken folder.

**Comment by johnnywo** [comment]
I manage those pdf templates from backend - do you think it is worth a try to make the **view** approach? Does that make a difference?

**Comment by mplodowski** [comment]
I checked this today and I found what is causing this issue. Probably this is also the bug you found. In my case it was the `setOptions` method called on PDF wrapper. 

First, please update plugin to version 4.0.8.

If you are using plugin to generate pdfs in your custom plugins than please read the [Update Guide](https://github.com/mplodowski/dynamicpdf-plugin/blob/master/UPGRADE.md#upgrading-to-408) 

If you only generate pdfs in plugin Settings than all should be fixed after update. Just set the fonts paths like they were before.

Let me know if this fix the issue for you.

**Comment by johnnywo** [comment]
thank you for investigating - just updated to v4.0.8 - and specified options for PDF Wrapper like:

```php           
PDF::loadTemplate('a711.offer::pdf.preisetikett', $data)  
         ->setDpi(300)    
         ->setTempDir($temp_path)  
         ->setIsRemoteEnabled(true)  
         ->save($pdf_file_name_directory);
```

at the moment it generates the PDF File with background-image and text, but my css styles are completely ignored..

**Comment by mplodowski** [comment]
How do you add styles? 

In CSS section of the template or using external file?

**Comment by johnnywo** [comment]
in the CSS Section of the template in backend here:
/backend/renatio/dynamicpdf/layouts/update/2#secondarytab-renatiodynamicpdflangtemplatescontent-css

**Comment by mplodowski** [comment]
Hmm, I just check and set color for h1 and it is working for me.

If you want me to investigate more into this, than you will have to send me all the code you use to generate template. It can be here or by email.

**Comment by mplodowski** [comment]
Try this:

```
PDF::loadTemplate('a711.offer::pdf.preisetikett', $data)  
         ->setDpi(300)    
         ->setTempDir($temp_path)  
         ->setIsRemoteEnabled(true)  
         ->save($pdf_file_name_directory);
```

Try to use `src: url('storage/fonts/Montserrat-Regular.ttf');`.

Let me know if this works.

**Comment by johnnywo** [comment]
okay, .. I really don't know what I have done now different than before, but now it is working as expected (just registered new template and layout and played around) Thank you!
