### ISSUE TITLE
The images are no longer printed

### ISSUE THREAD

**Issue by adoudiet** [mplodowski/dynamicpdf-plugin#89]
Hello,
After the latest updates the image no longer print on the pdf. See the code below and screenshots.
CODE:
![code](https://user-images.githubusercontent.com/8739002/100981646-5a5e1f00-3547-11eb-9dd2-aacefd1b1637.png)
ERROR
![error](https://user-images.githubusercontent.com/8739002/100980942-52ea4600-3546-11eb-8caf-d93db99b6b8e.png)
NORMAL (Before update)
![normal](https://user-images.githubusercontent.com/8739002/100980954-5978bd80-3546-11eb-9168-c68cc3c56c3d.png)

Thanks for your services. Greetings Alain Doudiet

**Comment by mplodowski** [comment]
I checked this today and I found what is causing this issue. Probably this is also the bug you found. In my case it was the `setOptions` method called on PDF wrapper. 

First, please update plugin to version 4.0.8.

If you are using plugin to generate pdfs in your custom plugins than please read the [Update Guide](https://github.com/mplodowski/dynamicpdf-plugin/blob/master/UPGRADE.md#upgrading-to-408) 

If you only generate pdfs in plugin Settings than all should be fixed after update.

Let me know if this fix the issue for you.
