### ISSUE TITLE
No query results for model [Renatio\DynamicPDF\Models\Template]

### ISSUE THREAD

**Issue by sattar-kuet** [mplodowski/dynamicpdf-plugin#91]
I install DynamicPDF in my octoberapplication. I followed every steps of `https://octobercms.com/plugin/renatio-dynamicpdf#registering-pdf-templates-and-layouts.

And just create a sample file to test:
```
title = "pdf"
url = "/dashboard/pdf"
layout = "admin"
is_hidden = 0
role = 0
permission = 0
anonymous_only = 0
logged_only = 1
child_of = "dashboard"
hide_crumb = 0
remove_crumb_trail = 0
crumb_disabled = 0

[viewBag]
==
<?php
use Renatio\DynamicPDF\Classes\PDF;

function onStart()
{
    return PDF::loadTemplate('renatio::invoice')->stream();
}
?>
==

<h1>Hello</h1>
```

But when I browse this page I am getting the following error:

```
No query results for model [Renatio\DynamicPDF\Models\Template].
C:\xampp\htdocs\courierdemo.itscholarbd.com\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php line 479
```
I struggled to fix this issue for the whole day. there are many sample code I tested, nothing works. Any idea?

**Comment by sattar-kuet** [comment]
I resolved! thanks

**Comment by janvandelaar** [comment]
Nice! But how was the fix done???

**Comment by chocolata** [comment]
I'd also like to know how this was resolved?
