### ISSUE TITLE
Encoding issue when using |raw twig filter.

### ISSUE THREAD

**Issue by zsso** [mplodowski/dynamicpdf-plugin#94]
There is an ecoding problem when using twig `|raw` filter layout files. Characters "ő" and "ű" are converted to "?", but only with PDF conversion, HTML preview is ok.

Layout code to reproduce:
```
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        <title>Document</title>
            <style type="text/css" media="screen">
            {{ css|raw }}
        </style>
    </head>
    <body>
        {{ '<h1 class="text-primary">őúéáűíóü</h1>'|raw }}       
    </body>
</html>
```

On update layout page, if PreviewHTML is used, everything is ok, but PreviewPDF produces the issue, also when downloading PDF, characters are wrong.

[Stackoverflow discussing here.](https://stackoverflow.com/questions/69629169/does-twig-raw-filter-do-any-encoding)

**Comment by mplodowski** [comment]
Hi,

sorry for late response. The reason you don't see those characters is using default font which does not support UTF-8.

You can use font, that plugin ships with.  Add following code in CSS section of the layout:

```
@font-face {
    font-family: 'Open Sans';
    src: url({{ 'plugins/renatio/dynamicpdf/assets/fonts/OpenSans-Regular.ttf'|app }});
}

@font-face {
    font-family: 'Open Sans';
    font-weight: bold;
    src: url({{ 'plugins/renatio/dynamicpdf/assets/fonts/OpenSans-Bold.ttf'|app }});
}

@font-face {
    font-family: 'Open Sans';
    font-style: italic;
    src: url({{ 'plugins/renatio/dynamicpdf/assets/fonts/OpenSans-Italic.ttf'|app }});
}

@font-face {
    font-family: 'Open Sans';
    font-style: italic;
    font-weight: bold;
    src: url({{ 'plugins/renatio/dynamicpdf/assets/fonts/OpenSans-BoldItalic.ttf'|app }});
}

body {
    font-family: 'Open Sans', sans-serif;
    font-size: 16px;
}
```

**Comment by zsso** [comment]
Hi,

Thank you. I don't know how could I miss that detail...

Have a nice day!

ProtonMail alkalmazásból küldve

-------- Eredeti üzenet --------
Be 2021. nov. 24. 18:27, Michał Płodowski írta:
