### ISSUE TITLE
Deprecated in PHP 8.0

### ISSUE THREAD

**Issue by AIC-BV** [mplodowski/dynamicpdf-plugin#95]
Required paremeters must come before optional parameters:
`function __construct($paper = "letter", $orientation = "portrait", Dompdf $dompdf);`
Must be changed into:
`function __construct(Dompdf $dompdf, $paper = "letter", $orientation = "portrait");`

(3x)

**Comment by mplodowski** [comment]
There is no such code in my plugin. The latest version is tested with PHP 8.0 and it works.

**Comment by AIC-BV** [comment]
Ok weird.
Probably has something to do with WinterCMS <-> OctoberCMS then.
Just installed it through backend->plugins and that was the error and fix.

**Comment by mplodowski** [comment]
From version 5.0.1 this plugin dropped support for October 1.x (WinterCMS included).
