### ISSUE TITLE
Not working with OctoberCMS 3.0

### ISSUE THREAD

**Issue by AIC-BV** [mplodowski/dynamicpdf-plugin#99]
**Describe the bug**
DynamicPDF is not working with OctoberCMS 3.0.
OctoberCMS 3.0 requires Laravel 9.

To add support for Laravel 9 you need to update BarryVDH-DomPDF to version 1.0.0 (now 0.9.0).
See: https://github.com/barryvdh/laravel-dompdf/tree/v1.0.0

**Comment by mplodowski** [comment]
Please upgrade plugin to version 6.0.
